name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t alm5/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true alm5/react-test npm test

      - name: Set Service Key
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-476522

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-k8s
          location: us-central1

      - name: Build
        run: |-
          docker build -t alm5/multi-client:latest -t alm5/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t alm5/multi-server:latest -t alm5/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t alm5/multi-worker:latest -t alm5/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push alm5/multi-client:latest
          docker push alm5/multi-server:latest
          docker push alm5/multi-worker:latest

          docker push alm5/multi-client:${{ env.SHA }}
          docker push alm5/multi-server:${{ env.SHA }}
          docker push alm5/multi-worker:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=alm5/multi-server:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=alm5/multi-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=alm5/multi-worker:${{ env.SHA }}
