name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - run: docker build -t alm5/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true alm5/react-test npm test

      - run: docker build -t alm5/multi-client ./client
      - run: docker build -t alm5/multi-nginx ./nginx
      - run: docker build -t alm5/multi-server ./server
      - run: docker build -t alm5/multi-worker ./worker

      - run: docker push alm5/multi-client
      - run: docker push alm5/multi-nginx
      - run: docker push alm5/multi-server
      - run: docker push alm5/multi-worker
